version: "3"
services:
  app-web:
    image: kianahub03/composeencuestap4:v1.0
    ports:
      - 80:8080
    environment:
      - spring.datasource.url=jdbc:mysql://base-datos:3306/barcampcomposedb
    networks:
      - red-app
    depends_on:
      - base-datos

  base-datos:
    image:
      mysql:5.7.26
    ports:
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user1
      - MYSQL_DATABASE=barcampcomposedb
    volumes:
      - ~/datadir_mysql:/var/lib/mysql
    networks:
      - red-app
networks:
  red-app: